--CREATE DATABASE GROUPBYHAVINGVIEW
--USE GROUPBYHAVINGVIEW

CREATE TABLE USERS
(
	ID INT PRIMARY KEY IDENTITY,
	NAME NVARCHAR(50) NOT NULL ,
	SURNAME NVARCHAR(50) DEFAULT'XXX' ,
	USERNAME NVARCHAR(50) NOT NULL UNIQUE,
	PASSWORD NVARCHAR (50) NOT NULL,
	GENDER BIT NOT NULL
) 
CREATE TABLE ARTISTS
(
	ID INT PRIMARY KEY IDENTITY,
	NAME NVARCHAR (50) NOT NULL,
	SURNAME NVARCHAR (50) DEFAULT 'XXX',
	BIRTHDAY NVARCHAR (20) NOT NULL,
	GENDER BIT NOT NULL

)
CREATE TABLE CATEGORIES
(
	ID INT PRIMARY KEY IDENTITY,
	NAME NVARCHAR (50) NOT NULL UNIQUE,

)
CREATE TABLE MUSICS
(
	ID INT  PRIMARY KEY IDENTITY,
	NAME NVARCHAR(50) NOT NULL UNIQUE,
	DURATION VARCHAR(10) NOT NULL,
	ARTISTID INT NOT NULL REFERENCES ARTISTS(ID),
	CATEGORYID INT REFERENCES CATEGORIES(ID)
	
)
CREATE TABLE PLAYLISTS
(
	ID INT PRIMARY KEY IDENTITY,
	USERID INT NOT NULL REFERENCES USERS(ID),
	MUSICID INT NOT NULL REFERENCES MUSICS(ID)
)
INSERT INTO Users VALUES
(N'ANAR',N'QASIMZADA','ANAR22','BHBHBAB',1),(N'NURLAN',N'ABBASOV','ABBSO123','SHBHH',1),(N'RAMAL',N'ISMAYILZADE','ISMYLZ','BHSBYSB',1)

INSERT INTO ARTISTS VALUES
('RADIOHEAD','XXX','12/2/1990',1),('THE SMITHS','XXX','21/3/1984',1)

INSERT INTO CATEGORIES VALUES
('Metalic'),('Rock'),('Pop'),('Rap')

INSERT INTO MUSICS VALUES
('CREEP','3;19',2,2),('BACK TO THE OLD HOUSE','3:47',2,4)

INSERT INTO PLAYLISTS VALUES
(1,1),(1,2),(2,1)

CREATE VIEW CallDetail AS 
SELECT m.[Name] AS MusicName, m.Duration AS Duration, c.[Name] AS Category, a.[Name] + ' ' + a.Surname AS Fullname FROM Categories AS c
JOIN Musics AS m
ON m.CategoryId=c.Id
JOIN Artists AS a
ON a.Id=m.ArtistId;
	
SELECT * FROM CallDetail

SELECT u.[Name] + ' ' + u.Surname AS Fullname, m.[Name] AS MusicName  FROM Users AS u
JOIN Playlists AS p
ON p.UserId=u.Id
JOIN Musics AS m
ON u.Id=p.MusicId

SELECT * FROM Musics AS m
ORDER BY m.Duration ASC

SELECT TOP 1 Artists.Name + ' ' + Artists.Surname AS Fullname, COUNT(*) AS NumOfSongs
FROM Artists
JOIN Musics ON Artists.Id = Musics.ArtistID
GROUP BY Artists.Name, Artists.Surname
ORDER BY NumOfSongs DESC;
